"""Initial

Revision ID: 0001
Revises:
Create Date: 2026-05-21 21:59:56.047733

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=10), server_default="en", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_user_name"), ["user_name"], unique=True)

    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("bank", sa.Enum("ING", "DKB", "DFS", "TRADE_REPUBLIC", name="bankprovider"), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("session_state", sa.JSON(), nullable=True),
        sa.Column("last_fetching_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requires_two_factor_authentication", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("remember_me", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_token_hash"), ["token_hash"], unique=True)

    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.Column("balance_factor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "account_balance_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "date", name="uq_balance_snapshot_account_date"),
    )
    with op.batch_alter_table("account_balance_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_balance_snapshots_account_id"), ["account_id"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("other_party", sa.String(), nullable=True),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "INCOMING",
                "OUTGOING",
                "BUY",
                "SELL",
                "DEPOSIT",
                "REMOVAL",
                "DIVIDEND",
                "INTEREST",
                "INTEREST_CHARGE",
                "TAXES",
                "TAX_REFUND",
                "FEES",
                "FEES_REFUND",
                "SPINOFF",
                "SPLIT",
                "SWAP",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                "UNKNOWN",
                name="transactiontype",
            ),
            nullable=True,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "SALARY",
                "ALLOWANCE",
                "PENSION",
                "REIMBURSEMENT",
                "INTEREST",
                "INVESTMENT",
                "SUBSCRIPTIONS",
                "RENT",
                "UTILITIES",
                "CAR",
                "FUEL",
                "FITNESS",
                "ONLINE_SHOPPING",
                "SUPERMARKET",
                "DRUGSTORE",
                "RESTAURANTS",
                "PERSONAL_CARE",
                "CLOTHING",
                "GIFTS",
                "ENTERTAINMENT",
                "FEES",
                "SAVINGS",
                "WITHDRAWAL",
                "TRANSFER",
                "UNKNOWN",
                name="transactioncategory",
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    with op.batch_alter_table("account_balance_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_balance_snapshots_account_id"))

    op.drop_table("account_balance_snapshots")
    op.drop_table("accounts")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_token_hash"))

    op.drop_table("sessions")
    op.drop_table("credentials")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_user_name"))

    op.drop_table("users")
    # ### end Alembic commands ###
