[config]
extend = true

[[rules]]
id = "custom-product-id"
description = "Check for fints product_id"
regex = '''(?i)product_id\s*[:=]\s*['"]([^$\{\s][^'"\n]{2,})['"]'''
secretGroup = 1

[allowlist]
paths = [
    '''(^|/)\.venv/''',
]