services:
  app:
    image: ghcr.io/felixschndr/quaestor
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data # Ensure that the user with the ID 1000 owns this directory recursively on the host! See README.md
      # - quaestor-data:/data # See the README for this
    environment:
      HOST: 0.0.0.0
      DATABASE_ENCRYPTION_KEY: ${DATABASE_ENCRYPTION_KEY}
      # See the README for more env variables
    restart: on-failure
    cap_drop:
      - ALL

#volumes:
#  quaestor-data:
