// GENERATED by scripts/checks/generate_frontend_categories.py --> do not edit.
// Single source of truth: TransactionCategory in source/backend/models/transactions/transaction_category.py

export const TRANSACTION_CATEGORIES = [
  'SALARY',
  'ALLOWANCE',
  'PENSION',
  'SIDE_INCOME',
  'REIMBURSEMENT',
  'INTEREST',
  'INVESTMENT',
  'SUBSCRIPTIONS',
  'RENT',
  'UTILITIES',
  'TRAVEL',
  'FUEL',
  'FITNESS',
  'ONLINE_SHOPPING',
  'SUPERMARKET',
  'DRUGSTORE',
  'RESTAURANTS',
  'PERSONAL_CARE',
  'CLOTHING',
  'GIFTS',
  'ENTERTAINMENT',
  'FEES',
  'SAVINGS',
  'WITHDRAWAL',
  'DEPOSIT',
  'TRANSFER',
  'UNKNOWN',
] as const

export type TransactionCategory = (typeof TRANSACTION_CATEGORIES)[number]
