import {
  ArrowDownLeft,
  ArrowRightFromLine,
  ArrowRightToLine,
  ArrowUpRight,
  Banknote,
  CircleSlash,
  Coins,
  Divide,
  Landmark,
  Percent,
  Receipt,
  Replace,
  Split,
  TrendingDown,
  TrendingUp,
  type LucideIcon,
} from 'lucide-react'

export const TRANSACTION_TYPE_ICONS: Record<string, LucideIcon> = {
  INCOMING: ArrowDownLeft,
  OUTGOING: ArrowUpRight,
  BUY: TrendingUp,
  SELL: TrendingDown,
  DEPOSIT: Landmark,
  REMOVAL: Banknote,
  DIVIDEND: Percent,
  INTEREST: Percent,
  INTEREST_CHARGE: Percent,
  TAXES: Receipt,
  TAX_REFUND: Receipt,
  FEES: Coins,
  FEES_REFUND: Coins,
  SPINOFF: Split,
  SPLIT: Divide,
  SWAP: Replace,
  TRANSFER_IN: ArrowRightToLine,
  TRANSFER_OUT: ArrowRightFromLine,
  ZERO: CircleSlash,
}
