#!/usr/bin/env python3

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from source.backend.helpers import get_frontend_source_path
from source.backend.models.transactions.transaction_category import TransactionCategory

OUTPUT = get_frontend_source_path() / "lib" / "transactionCategories.gen.ts"


def render() -> str:
    values = "\n".join(f"  '{category.value}'," for category in TransactionCategory)
    return (
        "// GENERATED by scripts/checks/generate_frontend_categories.py --> do not edit.\n"
        "// Single source of truth: TransactionCategory in source/backend/models/transactions/transaction_category.py\n"
        "\n"
        "export const TRANSACTION_CATEGORIES = [\n"
        f"{values}\n"
        "] as const\n"
        "\n"
        "export type TransactionCategory = (typeof TRANSACTION_CATEGORIES)[number]\n"
    )


def main() -> int:
    OUTPUT.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
