#!/usr/bin/env python3

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from source.backend.helpers import get_frontend_source_path
from source.backend.models.transactions.transaction_category import (
    CATEGORIES_BY_GROUP,
    CategoryGroup,
    TransactionCategory,
)

OUTPUT = get_frontend_source_path() / "lib" / "transactionCategories.gen.ts"


def _quoted_lines(values: list[str], indent: str = "  ") -> str:
    return "\n".join(f"{indent}'{value}'," for value in values)


def render() -> str:
    groups = "\n".join(
        f"  {group.value}: [\n{_quoted_lines([category.value for category in categories], indent='    ')}\n  ],"
        for group, categories in CATEGORIES_BY_GROUP.items()
    )
    return (
        "// GENERATED by scripts/checks/generate_frontend_categories.py --> do not edit.\n"
        "// Single source of truth: source/backend/models/transactions/transaction_category.py\n"
        "\n"
        "export const TRANSACTION_CATEGORIES = [\n"
        f"{_quoted_lines([category.value for category in TransactionCategory])}\n"
        "] as const\n"
        "\n"
        "export type TransactionCategory = (typeof TRANSACTION_CATEGORIES)[number]\n"
        "\n"
        "export const CATEGORY_GROUPS = [\n"
        f"{_quoted_lines([group.value for group in CategoryGroup])}\n"
        "] as const\n"
        "\n"
        "export type CategoryGroup = (typeof CATEGORY_GROUPS)[number]\n"
        "\n"
        "export const CATEGORIES_BY_GROUP: Record<CategoryGroup, readonly TransactionCategory[]> = {\n"
        f"{groups}\n"
        "}\n"
    )


def main() -> int:
    OUTPUT.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
