name: Run tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install backend dependencies
        run: poetry install --no-interaction --no-root

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: task backend:test
        run: task backend:test

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: pnpm/action-setup@v6.0.8
        with:
          version: 11

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: source/frontend/pnpm-lock.yaml

      - name: Install frontend dependencies
        working-directory: source/frontend
        run: pnpm install --frozen-lockfile

      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: task frontend:test
        run: task frontend:test
